services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=todo-notification'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5434:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
  notification-service-1:
    build: .
    container_name: notification-service-1
    ports:
      - "9086:8084"
    environment:
      - Name=instance1
    depends_on:
      - postgres
  notification-service-2:
    build: .
    container_name: notification-service-2
    ports:
      - "9087:8084"
    environment:
      - Name=instance2
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer-3
    ports:
      - 8084:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - notification-service-1
      - notification-service-2
