services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: notification

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-todo
    ports:
      - "5672:5672" # RabbitMQ protocol (AMQP)
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  notification-service-1:
    build: .
    container_name: notification-service-1
    ports:
      - "9089:8084"
    environment:
      - spring.data.mongodb.uri=mongodb://root:secret@mongo:27017/notification?authSource=admin
      - spring.data.mongodb.database=notification
      - spring.rabbitmq.host=rabbitmq-todo
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
      - Name=instance1
    depends_on:
      - mongo
      - rabbitmq

  notification-service-2:
    build: .
    container_name: notification-service-2
    ports:
      - "9088:8084"
    environment:
      - spring.data.mongodb.uri=mongodb://root:secret@mongo:27017/notification?authSource=admin
      - spring.data.mongodb.database=notification
      - spring.rabbitmq.host=rabbitmq-todo
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
      - Name=instance2
    depends_on:
      - mongo
      - rabbitmq

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer-notification
    ports:
      - "8084:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - notification-service-1
      - notification-service-2